# https://fabricmc.net/develop/

[versions]
fabricLoader = "0.18.1"
fabricApi = "0.139.2+1.21.11"
fabricMinecraft = "1.21.11-pre3"
fabricLanguageKotlin = "1.13.0+kotlin.2.1.0"
javatube = "6692a32"
lwjgl = "3.3.3"
utils = "1.3.1"
javacv = "1.5.12"
javacppPresets = "1.5.12"
ffmpegVersion = "7.1.1"
jna = "5.9.0"
jspecify = "1.0.0"
bstats = "3.1.0"

neoforge = "21.11.0-alpha.1.21.11-pre3.20251126.164358"

# Plugin versions
loom = "1.14.0-alpha.29"
moddev = "2.0.120"
shadow = "9.2.2"

[plugins]

[libraries]
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "fabricMinecraft" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
javatube = { module = "com.github.felipeucelli:javatube", version.ref = "javatube" }
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
utils = { module = "me.inotsleep:utils", version.ref = "utils" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacv" }
ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "javacppPresets" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jnaPlatform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
