# https://fabricmc.net/develop/

[versions]
fabricLoader = "0.18.1"
fabricApi = "0.139.1+1.21.11"
fabricMinecraft = "1.21.11-pre2"
javatube = "6692a32"
lwjgl = "3.3.3"
utils = "1.3.1"
javacv = "1.5.10"
javacppPresets = "1.5.10"
jna = "5.9.0"
jspecify = "1.0.0"

neoforge = "21.11.0-alpha.1.21.11-pre2.20251122.134508"

# Plugin versions
loom = "1.13.4"
moddev = "2.0.119"
shadow = "9.2.2"

[plugins]

[libraries]
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "fabricMinecraft" }
javatube = { module = "com.github.felipeucelli:javatube", version.ref = "javatube" }
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
utils = { module = "me.inotsleep:utils", version.ref = "utils" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacv" }
ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "javacppPresets" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jnaPlatform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
