# Check for the latest versions at https://fabricmc.net/develop/
# or https://mods.upcraft.dev/dev/versions

[versions]
fabricMinecraft = "1.21.11"
fabricLoader = "0.18.1"
fabricApi = "0.139.4+1.21.11"
fabricLanguageKotlin = "1.13.7+kotlin.2.2.21"
javatube = "29728b9"
utils = "1.3.1"
javacv = "1.5.12"
ffmpeg = "7.1.1"
jspecify = "1.0.0"
bstats = "3.1.0"
neoforge = "21.11.0-beta"
loom = "1.14.4"
moddev = "2.0.122"
shadow = "9.2.2"

[libraries]
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "fabricMinecraft" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
javatube = { module = "com.github.felipeucelli:javatube", version.ref = "javatube" }
utils = { module = "me.inotsleep:utils", version.ref = "utils" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacv" }
ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "javacv" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
