# https://fabricmc.net/develop/

[versions]
fabricLoader = "0.17.2"
fabricApi = "0.138.3+1.21.10"
fabricMinecraft = "1.21.10"
javatube = "6692a32"
lwjgl = "3.3.3"
utils = "1.3.1"
gst1 = "1.4.0"
jna = "5.9.0"

neoforge = "21.10.52-beta"

# plugin versions
loom = "1.13.4"
moddev = "2.0.119"
shadow = "9.2.2"

[plugins]

[libraries]
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "fabricMinecraft" }
javatube = { module = "com.github.felipeucelli:javatube", version.ref = "javatube" }
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
utils = { module = "me.inotsleep:utils", version.ref = "utils" }
gst1 = { module = "org.freedesktop.gstreamer:gst1-java-core", version.ref = "gst1" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jnaPlatform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }